const names = [
    { genre: 'f', singular: 'Flasche', plural: 'Flaschen', translation: 'Botella', image: 'flasche', lesson: 3 },
    { genre: 'm', singular: 'Kuli', plural: 'Kulis', translation: 'Boli', image: 'kuli', lesson: 3 },
    { genre: 'n', singular: 'Handy', plural: 'Handys', translation: 'Móvil', image: 'handy', lesson: 3 },
    { genre: 'm', singular: 'Radiergummi', plural: 'Radiergummis', translation: 'Goma de borrar', image: 'radiergummi', lesson: 3 },
    { genre: 'm', singular: 'Bleistift', plural: 'Bleistifte', translation: 'Lápiz', image: 'bleistift', lesson: 3 },
    { genre: 'n', singular: 'Buch', plural: 'Bücher', translation: 'Libro', image: 'buch', lesson: 3 },
    { genre: 'm', singular: 'Stuhl', plural: 'Stühle', translation: 'Silla', image: 'stuhl', lesson: 3 },
    { genre: 'n', singular: 'Tablet', plural: 'Tablets', translation: 'Tableta', image: 'tablet', lesson: 3 },
    { genre: 'm', singular: 'Tisch', plural: 'Tische', translation: 'Mesa', image: 'tisch', lesson: 3 },
    { genre: 'n', singular: 'Fenster', plural: 'Fenster', translation: 'Ventana', image: 'fenster', lesson: 3 },
    { genre: 'm', singular: 'Papierkorb', plural: 'Papierkörbe', translation: 'Papelera', image: 'papierkorb', lesson: 3 },
    { genre: 'f', singular: 'Tasche', plural: 'Taschen', translation: 'Bolso', image: 'tasche', lesson: 3 },
    { genre: 'n', singular: 'Heft', plural: 'Hefte', translation: 'Cuaderno', image: 'heft', lesson: 3 },
    { genre: 'f', singular: 'Tasse', plural: 'Tassen', translation: 'Taza', image: 'tasse', lesson: 3 },
    { genre: 'f', singular: 'Tafel', plural: 'Tafeln', translation: 'Pizarra / Tableta', image: '', lesson: 3 },
    { genre: 'f', singular: 'Lampe', plural: 'Lampen', translation: 'Lámpara', image: 'lampe', lesson: 3 },
    { genre: 'f', singular: 'Jacke', plural: 'Jacken', translation: 'Chaqueta', image: 'jacke', lesson: 3 },
    { genre: 'f', singular: 'Tür', plural: 'Türen', translation: 'Puerta', image: 'tur', lesson: 3 },
    { genre: 'm', singular: 'Kursraum', plural: 'Kursräume', translation: 'Aula', image: 'kursraum', lesson: 3 },
    { genre: 'f', singular: 'Wand', plural: 'Wände', translation: 'Pared', image: 'wand', lesson: 3 },
    { genre: 'm', singular: 'Boden', plural: 'Böden', translation: 'Suelo', image: 'boden', lesson: 3 },
    { genre: 'f', singular: 'Uhr', plural: 'Uhren', translation: 'Reloj', image: 'uhr', lesson: 3 },
    { genre: 'f', singular: 'Brille', plural: 'Brillen', translation: 'Gafas', image: 'brille', lesson: 3 },
    { genre: 'm', singular: 'Zettel', plural: 'Zettel', translation: 'Nota', image: 'zettel', lesson: 3 },
    { genre: 'f', singular: 'Zeitung', plural: 'Zeitungen', translation: 'Periódico', image: 'zeitung', lesson: 3 },
    { genre: 'n', singular: 'Bett', plural: 'Betten', translation: 'Cama', image: 'bett', lesson: 3 },
    { genre: 'n', singular: 'Flugzeug', plural: 'Flugzeuge', translation: 'Avión', image: 'flugzeug', lesson: 3 },
    { genre: 'n', singular: 'Kino', plural: 'Kinos', translation: 'Cine', image: 'kino', lesson: 3 },
    { genre: 'm', singular: 'Ball', plural: 'Bälle', translation: 'Pelota', image: 'ball', lesson: 3 },
    { genre: 'f', singular: 'Maus', plural: 'Mäuse', translation: 'Ratón', image: 'maus', lesson: 3 },
    { genre: 'n', singular: 'Auto', plural: 'Autos', translation: 'Coche', image: 'auto', lesson: 3 },
    { genre: 'f', singular: 'Tochter', plural: 'Töchter', translation: 'Hija', image: 'tochter', lesson: 3 },
    { genre: 'm', singular: 'Apfel', plural: 'Äpfel', translation: 'Manzana', image: 'apfel', lesson: 3 },
    { genre: 'n', singular: 'Bild', plural: 'Bilder', translation: 'Cuadro', image: 'bild', lesson: 3 },
    { genre: 'm', singular: 'Schrank', plural: 'Schränke', translation: 'Armario', image: 'schrank', lesson: 3 },
    { genre: 'n', singular: 'Motorrad', plural: 'Motorräder', translation: 'Motocicleta', image: 'motorrad', lesson: 3 },
    { genre: 'm', singular: 'Sohn', plural: 'Söhne', translation: 'Hijo', image: 'sohn', lesson: 3 },
    { genre: 'm', singular: 'Monat', plural: 'Monate', translation: 'Mes', image: 'monat', lesson: 3 },
    { genre: 'm', singular: 'Salat', plural: 'Salate', translation: 'Lechuga', image: 'salat', lesson: 3 },
    { genre: 'n', singular: 'Glas', plural: 'Gläser', translation: 'Vaso', image: 'glas', lesson: 3 },
    { genre: 'f', singular: 'Rechnung', plural: 'Rechnungen', translation: 'Cálculo', image: 'rechnung', lesson: 3 },
    { genre: 'f', singular: 'Zahl', plural: 'Zahlen', translation: 'Número', image: 'zahl', lesson: 3 },
    { genre: 'f', singular: 'Süßigkeit', plural: 'Süßigkeiten', translation: 'Golosina', image: 'sussigkeit', lesson: 3 },
    { genre: 'n', singular: 'Mäppchen', plural: 'Mäppchen', translation: 'Estuche', image: 'mappchen', lesson: 3 },
    { genre: 'n', singular: 'Taschentuch', plural: 'Taschentücher', translation: 'Pañuelo', image: 'taschentuch', lesson: 3 },
    { genre: 'm', singular: 'Lutscher', plural: 'Lutscher', translation: 'Piruleta', image: 'lutscher', lesson: 3 },
    { genre: 'm', singular: 'Rucksack', plural: 'Rucksäcke', translation: 'Mochila', image: 'rucksack', lesson: 3 },
    { genre: 'm', singular: 'Computer', plural: 'Computer', translation: 'Ordenador', image: 'computer', lesson: 3 },
    { genre: 'm', singular: 'Laptop', plural: 'Laptops', translation: 'Ordenador portátil', image: 'laptop', lesson: 3 },
    { genre: 'm', singular: 'Spitzer', plural: 'Spitzer', translation: 'Sacapuntas', image: 'spitzer', lesson: 3 },
    { genre: 'm', singular: 'Kopfhörer', plural: 'Kopfhörer', translation: 'Auriculares', image: 'kopfhorer', lesson: 3 },
    { genre: 'f', singular: 'Geige', plural: 'Geigen', translation: 'Violín', image: 'geige', lesson: 3 },
    { genre: 'm', singular: 'Füller', plural: 'Füller', translation: 'Pluma estilográfica', image: 'fuller', lesson: 3 },
    { genre: 'f', singular: 'Stadt', plural: 'Städte', translation: 'Ciudad', image: 'stadt', lesson: 3 },
    { genre: 'f', singular: 'Pizza', plural: 'Pizzen', translation: 'Pizza', image: 'pizza', lesson: 3 },
    { genre: 'm', singular: 'Schuh', plural: 'Schuhe', translation: 'Zapato', image: 'schuh', lesson: 4 },
    { genre: 'n', singular: 'Ladekabel', plural: 'Ladekabel', translation: 'Cargador', image: 'ladekabel', lesson: 4 },
    { genre: 'm', singular: 'USB-Stick', plural: 'USB-Sticks', translation: 'Memoria USB', image: 'usb-stick', lesson: 4 },
    { genre: 'm', singular: 'Hut', plural: 'Hüte', translation: 'Sombrero', image: 'hut', lesson: 4 },
    { genre: 'n', singular: 'Kleid', plural: 'Kleider', translation: 'Vestido', image: 'kleid', lesson: 4 },
    { genre: 'm', singular: 'Lippenstift', plural: 'Lippenstifte', translation: 'Pintalabios', image: 'lippenstift', lesson: 4 },
    { genre: 'f', singular: 'Sonnenbrille', plural: 'Sonnenbrillen', translation: 'Gafas de sol', image: 'sonnenbrille', lesson: 4 },
    { genre: 'f', singular: 'Batterie', plural: 'Batterien', translation: 'Pila', image: 'batterie', lesson: 4 },
    { genre: 'f', singular: 'Handyhülle', plural: 'Handyhüllen', translation: 'Funda de móvil', image: 'handyhulle', lesson: 4 },
    { genre: 'f', singular: 'Hose', plural: 'Hosen', translation: 'Pantalón', image: 'hose', lesson: 4 },
    { genre: 'f', singular: 'Kette', plural: 'Ketten', translation: 'Cadena', image: 'kette', lesson: 4 },
    { genre: 'm', singular: 'Ring', plural: 'Ringe', translation: 'Anillo', image: 'ring', lesson: 4 },
    { genre: 'm', singular: 'Koffer', plural: 'Koffer', translation: 'Maleta', image: 'koffer', lesson: 4 },
    { genre: 'n', singular: 'Spielzeug', plural: 'Spielzeuge', translation: 'Juguete', image: 'spielzeug', lesson: 4 },
    { genre: 'm', singular: 'Mantel', plural: 'Mäntel', translation: 'Abrigo', image: 'mantel', lesson: 4 },
    { genre: 'm', singular: 'Pullover', plural: 'Pullover', translation: 'Jersey', image: 'pullover', lesson: 4 },
    { genre: 'n', singular: 'T-Shirt', plural: 'T-Shirts', translation: 'Camiseta', image: 't-shirt', lesson: 4 },
    { genre: 'f', singular: 'Bluse', plural: 'Blusen', translation: 'Blusa', image: 'bluse', lesson: 4 },
    { genre: 'n', singular: 'Hemd', plural: 'Hemden', translation: 'Camisa', image: 'hemd', lesson: 4 },
    { genre: 'm', singular: 'Anzug', plural: 'Anzüge', translation: 'Traje', image: 'anzug', lesson: 4 },
    { genre: 'm', singular: 'Stiefel', plural: 'Stiefel', translation: 'Bota', image: 'stiefel', lesson: 4 },
    { genre: 'f', singular: 'Mütze', plural: 'Mützen', translation: 'Gorro', image: 'mutze', lesson: 4 },
    { genre: 'm', singular: 'Handschuh', plural: 'Handschuhe', translation: 'Guante', image: 'handschuh', lesson: 4 },
    { genre: 'm', singular: 'Regenschirm', plural: 'Regenschirme', translation: 'Paraguas', image: 'regenschirm', lesson: 4 },
    { genre: 'm', singular: 'Rock', plural: 'Röcke', translation: 'Falda', image: 'rock', lesson: 4 },
    { genre: 'f', singular: 'Sonne', plural: 'Sonnen', translation: 'Sol', image: 'sonne', lesson: 4 },
    { genre: 'm', singular: 'Mond', plural: 'Monde', translation: 'Luna', image: 'mond', lesson: 4 },
    { genre: 'f', singular: 'Wolke', plural: 'Wolken', translation: 'Nube', image: 'wolke', lesson: 4 },
    { genre: 'm', singular: 'Himmel', plural: 'Himmel', translation: 'Cielo', image: 'himmel', lesson: 4 },
    { genre: 'm', singular: 'Laden', plural: 'Läden', translation: 'Tienda', image: 'laden', lesson: 4 },
    { genre: 'm', singular: 'Junge', plural: 'Jungen', translation: 'Niño', image: 'junge', lesson: 4 },
    { genre: 'n', singular: 'Mädchen', plural: 'Mädchen', translation: 'Niña', image: 'madchen', lesson: 4 },
    { genre: 'n', singular: 'Eis', plural: '', translation: 'Hielo / helado', image: '', lesson: 4 },
    { genre: 'n', singular: 'Fahrrad', plural: 'Fahrräder', translation: 'Bicicleta', image: 'fahrrad', lesson: 4 },
    { genre: 'm', singular: 'Schlüssel', plural: 'Schlüssel', translation: 'Llave', image: 'schlussel', lesson: 4 },
    { genre: 'f', singular: 'Taschenlampe', plural: 'Taschenlampen', translation: 'Linterna', image: 'taschenlampe', lesson: 4 },
    { genre: 'f', singular: 'Kamera', plural: 'Kameras', translation: 'Cámara', image: 'kamera', lesson: 4 },
    { genre: 'f', singular: 'Schwester', plural: 'Schwestern', translation: 'Hermana', image: '', lesson: 4 },
    { genre: 'm', singular: 'Bruder', plural: 'Brüder', translation: 'Hermano', image: '', lesson: 4 },
    { genre: 'n', singular: 'Schiff', plural: 'Schiffe', translation: 'Barco', image: 'schiff', lesson: 4 },
    { genre: 'm', singular: 'Tee', plural: 'Tees', translation: 'Té', image: 'tee', lesson: 4 },
    { genre: 'm', singular: 'Kaffee', plural: 'Kaffees', translation: 'Café', image: 'kaffee', lesson: 4 },
    { genre: 'm', singular: 'Traum', plural: 'Träume', translation: 'Sueño', image: '', lesson: 4 },
    { genre: 'm', singular: 'Flohmarkt', plural: 'Flohmärkte', translation: 'Mercadillo', image: 'flohmarkt', lesson: 4 },
    { genre: 'n', singular: 'Theater', plural: 'Theater', translation: 'Teatro', image: 'theater', lesson: 4 },
    { genre: 'm', singular: 'Hafen', plural: 'Häfen', translation: 'Puerto', image: 'hafen', lesson: 4 },
    { genre: 'n', singular: 'Wort', plural: 'Worte', translation: 'Palabra', image: '', lesson: 4 },
    { genre: 'm', singular: 'Satz', plural: 'Sätze', translation: 'Frase', image: '', lesson: 4 },
    { genre: 'n', singular: 'Wunder', plural: 'Wunder', translation: 'Milagro', image: '', lesson: 4 },
    { genre: 'f', singular: 'Schere', plural: 'Scheren', translation: 'Tijeras', image: 'schere', lesson: 4 },
    { genre: 'f', singular: 'Tintenpatrone', plural: 'Tintenpatronen', translation: 'Cartucho de tinta', image: '', lesson: 4 },
    { genre: 'm', singular: 'Taschenrechner', plural: 'Taschenrechner', translation: 'Calculadora', image: 'taschenrechner', lesson: 4 },
    { genre: 'f', singular: 'Kreide', plural: 'Kreiden', translation: 'Tiza', image: 'kreide', lesson: 4 },
    { genre: 'm', singular: 'Kleber', plural: 'Kleber', translation: 'Pegamento', image: 'kleber', lesson: 4 },
    { genre: 'n', singular: 'Geodreieck', plural: 'Geodreiecke', translation: 'Escuadra', image: 'geodreieck', lesson: 4 },
    { genre: 'f', singular: 'Büroklammer', plural: 'Büroklammern', translation: 'Clip', image: 'buroklammer', lesson: 4 },
    { genre: 'n', singular: 'Wörterbuch', plural: 'Wörterbücher', translation: 'Diccionario', image: 'worterbuch', lesson: 4 },
    { genre: 'n', singular: 'Lineal', plural: 'Lineale', translation: 'Regla', image: 'lineal', lesson: 4 },
    { genre: 'm', singular: 'Preis', plural: 'Preise', translation: 'Precio', image: 'preis', lesson: 4 },
    { genre: 'n', singular: 'Geschäft', plural: 'Geschäfte', translation: 'Negocio', image: '', lesson: 4 },
    { genre: 'f', singular: 'Fußgängerzone', plural: 'Fußgängerzonen', translation: 'Zona peatonal', image: 'fussgangerzone', lesson: 4 },
    { genre: 'f', singular: 'Umfrage', plural: 'Umfragen', translation: 'Encuesta', image: 'umfrage', lesson: 4 },
    { genre: 'n', singular: 'Geschenk', plural: 'Geschenke', translation: 'Regalo', image: 'geschenk', lesson: 5 },
    { genre: 'm', singular: 'Helm', plural: 'Helme', translation: 'Casco', image: 'helm', lesson: 5 },
    { genre: 'n', singular: 'Sofa', plural: 'Sofas', translation: 'Sofá', image: 'sofa', lesson: 5 },
    { genre: 'n', singular: 'Wohnzimmer', plural: 'Wohnzimmer', translation: 'Cuarto de estar', image: '', lesson: 5 },
    { genre: 'm', singular: 'Schlittschuh', plural: 'Schlittschuhe', translation: 'Patín de hielo', image: 'schlittschuh', lesson: 5 },
    { genre: 'm', singular: 'Film', plural: 'Filme', translation: 'Película', image: '', lesson: 5 },
    { genre: 'f', singular: 'Vermutung', plural: 'Vermutungen', translation: 'Suposición', image: '', lesson: 5 },
    { genre: 'n', singular: 'Fernseher', plural: 'Fernseher', translation: 'Televisión', image: 'fernseher', lesson: 5 },
    { genre: 'f', singular: 'Tabelle', plural: 'Tabellen', translation: 'Tabla', image: '', lesson: 5 },
    { genre: 'f', singular: 'Wiederholung', plural: 'Wiederholungen', translation: 'Repetición', image: '', lesson: 5 },
    { genre: 'f', singular: 'Gitarre', plural: 'Gitarren', translation: 'Guitarra', image: 'gitarre', lesson: 5 },
    { genre: 'n', singular: 'Schach', plural: '', translation: 'Ajedrez', image: 'schach', lesson: 5 },
    { genre: 'f', singular: 'Küche', plural: 'Küchen', translation: 'Cocina', image: 'kuche', lesson: 5 },
    { genre: 'f', singular: 'Zeit', plural: 'Zeiten', translation: 'Tiempo', image: '', lesson: 5 },
    { genre: 'f', singular: 'Freizeit', plural: '', translation: 'Tiempo libre', image: '', lesson: 5 },
    { genre: 'n', singular: 'Hobby', plural: 'Hobbys', translation: 'Hobby', image: '', lesson: 5 },
    { genre: 'n', singular: 'Wochenende', plural: 'Wochenenden', translation: 'Fin de semana', image: '', lesson: 5 },
    { genre: 'f', singular: 'Woche', plural: 'Wochen', translation: 'Semana', image: '', lesson: 5 },
    { genre: 'n', singular: 'Klavier', plural: 'Klaviere', translation: 'Piano', image: 'klavier', lesson: 5 },
    { genre: 'f', singular: 'Mutter', plural: 'Mütter', translation: 'Madre', image: '', lesson: 5 },
    { genre: 'm', singular: 'Vater', plural: 'Väter', translation: 'Padre', image: '', lesson: 5 },
    { genre: 'f', singular: 'Farbe', plural: 'Farben', translation: 'Color', image: '', lesson: 5 },
    { genre: 'f', singular: 'Jahreszeit', plural: 'Jahreszeiten', translation: 'Estación del año', image: '', lesson: 5 },
    { genre: 'm', singular: 'Frühling', plural: 'Frühlinge', translation: 'Primavera', image: '', lesson: 5 },
    { genre: 'm', singular: 'Sommer', plural: 'Sommer', translation: 'Verano', image: '', lesson: 5 },
    { genre: 'm', singular: 'Herbst', plural: 'Herbste', translation: 'Otoño', image: '', lesson: 5 },
    { genre: 'm', singular: 'Winter', plural: 'Winter', translation: 'Invierno', image: '', lesson: 5 },
    { genre: 'f', singular: 'Information', plural: 'Informationen', translation: 'Información', image: '', lesson: 5 },
    { genre: 'm', singular: 'Tag', plural: 'Tage', translation: 'Día', image: '', lesson: 5 },
    { genre: 'm', singular: 'Montag', plural: 'Montage', translation: 'Lunes', image: '', lesson: 5 },
    { genre: 'm', singular: 'Dienstag', plural: 'Dienstage', translation: 'Martes', image: '', lesson: 5 },
    { genre: 'm', singular: 'Mittwoch', plural: 'Mittwoche', translation: 'Miércoles', image: '', lesson: 5 },
    { genre: 'm', singular: 'Donnerstag', plural: 'Donnerstage', translation: 'Jueves', image: '', lesson: 5 },
    { genre: 'm', singular: 'Freitag', plural: 'Freitage', translation: 'Viernes', image: '', lesson: 5 },
    { genre: 'm', singular: 'Samstag', plural: 'Samstage', translation: 'Sábado', image: '', lesson: 5 },
    { genre: 'm', singular: 'Sonntag', plural: 'Sonntage', translation: 'Domingo', image: '', lesson: 5 },
    { genre: 'f', singular: 'Wohnung', plural: 'Wohnungen', translation: 'Vivienda', image: '', lesson: 5 },
    { genre: 'm', singular: 'Ausflug', plural: 'Ausflüge', translation: 'Excursión', image: '', lesson: 5 },
    { genre: 'm', singular: 'Alltag', plural: '', translation: 'Día de diario', image: '', lesson: 5 },
    { genre: 'n', singular: 'Interview', plural: 'Interviews', translation: 'Entrevista', image: '', lesson: 5 },
    { genre: 'f', singular: 'Sehenswürdigkeit', plural: 'Sehenswürdigkeiten', translation: 'Monumento', image: '', lesson: 5 },
    { genre: 'm', singular: 'Gast', plural: 'Gäste', translation: 'Invitado', image: '', lesson: 5 },
    { genre: 'n', singular: 'Kind', plural: 'Kinder', translation: 'Niño/a', image: '', lesson: 5 },
    { genre: 'p', singular: '', plural: 'Leute', translation: 'Gente', image: '', lesson: 5 },
    { genre: 'm', singular: 'Garten', plural: 'Gärten', translation: 'Jardín', image: '', lesson: 5 },
    { genre: 'f', singular: 'Ausstellung', plural: 'Ausstellungen', translation: 'Exposición', image: '', lesson: 5 },
    { genre: 'f', singular: 'Oper', plural: 'Opern', translation: 'Ópera', image: '', lesson: 5 },
    { genre: 'f', singular: 'Kunst', plural: 'Künste', translation: 'Arte', image: '', lesson: 5 },
    { genre: 'p', singular: '', plural: 'Eltern', translation: 'Padres', image: '', lesson: 6 },
    { genre: 'm', singular: 'Freund(in)', plural: 'Freunde', translation: 'Amigo', image: '', lesson: 6 },
    { genre: 'n', singular: 'Glück', plural: '', translation: 'Suerte', image: '', lesson: 6 },
    { genre: 'm', singular: 'Familienstand', plural: '', translation: 'Estado civil', image: '', lesson: 6 },
    { genre: 'm', singular: 'Großvater', plural: 'Großväter', translation: 'Abuelo', image: '', lesson: 6 },
    { genre: 'f', singular: 'Großmutter', plural: 'Großmütter', translation: 'Abuela', image: '', lesson: 6 },
    { genre: 'p', singular: '', plural: 'Großeltern', translation: 'Abuelos', image: '', lesson: 6 },
    { genre: 'p', singular: '', plural: 'Geschwister', translation: 'Hermanos', image: '', lesson: 6 },
    { genre: 'm', singular: 'Partner(in)', plural: 'Partner(in)', translation: 'Compañero', image: '', lesson: 6 },
    { genre: 'm', singular: 'Ehepartner(in)', plural: 'Ehepartner(in)', translation: 'Cónyuge', image: '', lesson: 6 },
    { genre: 'n', singular: 'Ausland', plural: '', translation: '(País) extranjero', image: '', lesson: 6 },
    { genre: 'f', singular: 'Endung', plural: 'Endungen', translation: 'Terminación', image: '', lesson: 6 },
    { genre: 'f', singular: 'Familie', plural: 'Familien', translation: 'Familia', image: '', lesson: 6 },
    { genre: 'n', singular: 'Baby', plural: 'Babys', translation: 'Bebé', image: '', lesson: 6 },
    { genre: 'f', singular: 'Sprechblase', plural: 'Sprechblasen', translation: 'Bocadillo (de cómic)', image: '', lesson: 6 },
    { genre: 'f', singular: 'Liebe', plural: '', translation: 'Amor', image: '', lesson: 6 },
    { genre: 'm', singular: 'Krieg', plural: 'Kriege', translation: 'Guerra', image: '', lesson: 6 },
    { genre: 'f', singular: 'Freiheit', plural: '', translation: 'Libertad', image: '', lesson: 6 },
    { genre: 'f', singular: 'Einladung', plural: 'Einladungen', translation: 'Invitación', image: '', lesson: 6 },
    { genre: 'f', singular: 'Party', plural: 'Partys', translation: 'Fiesta', image: '', lesson: 6 },
    { genre: 'f', singular: 'Nachricht', plural: 'Nachrichten', translation: 'Noticia', image: '', lesson: 6 },
    { genre: 'm', singular: 'Brief', plural: 'Briefe', translation: 'Carta', image: '', lesson: 6 },
    { genre: 'f', singular: 'E-Mail', plural: 'E-Mails', translation: 'Correo electrónico', image: '', lesson: 6 },
    { genre: 'f', singular: 'Laune', plural: 'Launen', translation: 'Capricho', image: '', lesson: 6 },
    { genre: 'f', singular: 'Person', plural: 'Personen', translation: 'Persona', image: '', lesson: 6 },
    { genre: 'n', singular: 'Gespräch', plural: 'Gespräche', translation: 'Conversación', image: '', lesson: 6 },
    { genre: 'm', singular: 'Tourist(in)', plural: 'Touristen', translation: 'Turista', image: '', lesson: 6 },
    { genre: 'f', singular: 'Heimat', plural: 'Heimaten', translation: 'Patria', image: '', lesson: 6 },
    { genre: 'n', singular: 'Heute', plural: '', translation: 'Hoy', image: '', lesson: 6 },
    { genre: 'n', singular: 'Gestern', plural: '', translation: 'Ayer', image: '', lesson: 6 },
    { genre: 'm', singular: 'Geburtstag', plural: 'Geburtstage', translation: 'Cumpleaños', image: '', lesson: 6 },
    { genre: 'm', singular: 'Arbeitsplatz', plural: 'Arbeitsplätze', translation: 'Lugar de trabajo', image: '', lesson: 6 },
    { genre: 'm', singular: 'Tipp', plural: 'Tipps', translation: 'Consejo', image: '', lesson: 6 },
    { genre: 'f', singular: 'Praline', plural: 'Pralinen', translation: 'Bombón', image: '', lesson: 6 },
    { genre: 'n', singular: 'Geld', plural: '', translation: 'Dinero', image: '', lesson: 6 },
    { genre: 'm', singular: 'Chef', plural: 'Chefs', translation: 'Jefe', image: '', lesson: 6 },
    { genre: 'f', singular: 'Chefin', plural: 'Chefinen', translation: 'Jefa', image: '', lesson: 6 },
    { genre: 'f', singular: 'Blume', plural: 'Blumen', translation: 'Flor', image: '', lesson: 6 },
    { genre: 'n', singular: 'Land', plural: 'Länder', translation: 'País', image: '', lesson: 6 },
    { genre: 'f', singular: 'Katze', plural: 'Katzen', translation: 'Gato', image: '', lesson: 6 },
    { genre: 'm', singular: 'Deospray', plural: 'Deosprays', translation: 'Desodorante', image: '', lesson: 6 },
    { genre: 'f', singular: 'Karte', plural: 'Karten', translation: 'Entrada', image: '', lesson: 6 },
    { genre: 'p', singular: '', plural: 'Lebensmittel', translation: 'Alimentos', image: '', lesson: 7 },
    { genre: 'm', singular: 'Joghurt', plural: 'Joghurts', translation: 'Yogur', image: '', lesson: 7 },
    { genre: 'm', singular: 'Brei', plural: 'Breie', translation: 'Papilla', image: '', lesson: 7 },
    { genre: 'f', singular: 'Butter', plural: '', translation: 'Mantequilla', image: '', lesson: 7 },
    { genre: 'n', singular: 'Fleisch', plural: '', translation: 'Carne', image: '', lesson: 7 },
    { genre: 'n', singular: 'Ei', plural: 'Eier', translation: 'Huevo', image: '', lesson: 7 },
    { genre: 'f', singular: 'Wurst', plural: 'Würste', translation: 'Embutido / Salchicha', image: '', lesson: 7 },
    { genre: 'f', singular: 'Gurke', plural: 'Gurken', translation: 'Pepino', image: '', lesson: 7 },
    { genre: 'm', singular: 'Paprika', plural: 'Paprika(s)', translation: 'Pimiento', image: '', lesson: 7 },
    { genre: 'f', singular: 'Milch', plural: '', translation: 'Leche', image: '', lesson: 7 },
    { genre: 'n', singular: 'Wasser', plural: 'Wasser', translation: 'Agua', image: '', lesson: 7 },
    { genre: 'm', singular: 'Saft', plural: 'Säfte', translation: 'Zumo', image: '', lesson: 7 },
    { genre: 'f', singular: 'Marmelade', plural: 'Marmeladen', translation: 'Mermelada', image: '', lesson: 7 },
    { genre: 'f', singular: 'Tomate', plural: 'Tomaten', translation: 'Tomate', image: '', lesson: 7 },
    { genre: 'f', singular: 'Banane', plural: 'Bananen', translation: 'Plátano', image: '', lesson: 7 },
    { genre: 'm', singular: 'Käse', plural: 'Käse', translation: 'Queso', image: '', lesson: 7 },
    { genre: 'm', singular: 'Wein', plural: 'Weine', translation: 'Vino', image: '', lesson: 7 },
    { genre: 'n', singular: 'Bier', plural: 'Biere', translation: 'Cerveza', image: '', lesson: 7 },
    { genre: 'm', singular: 'Kühlschrank', plural: 'Kühlschränke', translation: 'Frigorífico', image: '', lesson: 7 },
    { genre: 'n', singular: 'Obst', plural: '', translation: 'Fruta', image: '', lesson: 7 },
    { genre: 'm', singular: 'Kakao', plural: 'Kakaos', translation: 'Cacao', image: '', lesson: 7 },
    { genre: 'f', singular: 'Nudel', plural: 'Nudeln', translation: 'Pasta', image: '', lesson: 7 },
    { genre: 'm', singular: 'Reis', plural: 'Reise', translation: 'Arroz', image: '', lesson: 7 },
    { genre: 'f', singular: 'Kartoffel', plural: 'Kartoffeln', translation: 'Patata', image: '', lesson: 7 },
    { genre: 'f', singular: 'Packung', plural: 'Packungen', translation: 'Paquete', image: '', lesson: 7 },
    { genre: 'f', singular: 'Tüte', plural: 'Tüten', translation: 'Bolsa', image: '', lesson: 7 },
    { genre: 'm', singular: 'Becher', plural: 'Becher', translation: 'Vaso / Tarrina', image: '', lesson: 7 },
    { genre: 'n', singular: 'Stück', plural: 'Stücke', translation: 'Pieza', image: '', lesson: 7 },
    { genre: 'f', singular: 'Dose', plural: 'Dosen', translation: 'Bote / Lata', image: '', lesson: 7 },
    { genre: 'n', singular: 'Netz', plural: 'Netze', translation: 'Red', image: '', lesson: 7 },
    { genre: 'f', singular: 'Schokolade', plural: 'Schokoladen', translation: 'Chocolate', image: '', lesson: 7 },
    { genre: 'm', singular: 'Mais', plural: 'Maise', translation: 'Maíz', image: '', lesson: 7 },
    { genre: 'm', singular: 'Chip', plural: 'Chips', translation: 'Patata frita (snack)', image: '', lesson: 7 },
    { genre: 'f', singular: 'Orange', plural: 'Orangen', translation: 'Naranja', image: '', lesson: 7 },
    { genre: 'f', singular: 'Birne', plural: 'Birnen', translation: 'Pera', image: '', lesson: 7 },
    { genre: 'n', singular: 'Frühstück', plural: 'Frühstücke', translation: 'Desayuno', image: '', lesson: 7 },
    { genre: 'n', singular: 'Brot', plural: 'Brote', translation: 'Pan', image: '', lesson: 7 },
    { genre: 'f', singular: 'Melone', plural: 'Melonen', translation: 'Melón', image: '', lesson: 7 },
    { genre: 'f', singular: 'Wassermelone', plural: 'Wassermelonen', translation: 'Sandía', image: '', lesson: 7 },
    { genre: 'f', singular: 'Erdbeere', plural: 'Erdbeeren', translation: 'Fresa', image: '', lesson: 7 },
    { genre: 'f', singular: 'Ananas', plural: 'Ananas', translation: 'Piña', image: '', lesson: 7 },
    { genre: 'f', singular: 'Zitrone', plural: 'Zitronen', translation: 'Limón', image: '', lesson: 7 },
    { genre: 'f', singular: 'Pflaume', plural: 'Pflaumen', translation: 'Ciruela', image: '', lesson: 7 },
    { genre: 'n', singular: 'Gemüse', plural: 'Gemüse', translation: 'Verdura', image: '', lesson: 7 },
    { genre: 'f', singular: 'Karotte / Möhre', plural: 'Karotten / Möhren', translation: 'Zanahoria', image: '', lesson: 7 },
    { genre: 'f', singular: 'Aubergine', plural: 'Auberginen', translation: 'Berenjena', image: '', lesson: 7 },
    { genre: 'f', singular: 'Zucchini', plural: 'Zucchini', translation: 'Calabacín', image: '', lesson: 7 },
    { genre: 'n', singular: 'Gewürz', plural: 'Gewürze', translation: 'Especia', image: '', lesson: 7 },
    { genre: 'f', singular: 'Bohne', plural: 'Bohnen', translation: 'Judía', image: '', lesson: 7 },
    { genre: 'm', singular: 'Kohl', plural: '', translation: 'Col', image: '', lesson: 7 },
    { genre: 'f', singular: 'Erbse', plural: 'Erbsen', translation: 'Guisante', image: '', lesson: 7 },
    { genre: 'f', singular: 'Hülsenfrucht', plural: 'Hülsenfrüchte', translation: 'Legumbre', image: '', lesson: 7 },
    { genre: 'f', singular: 'Linse', plural: 'Linsen', translation: 'Lenteja', image: '', lesson: 7 },
    { genre: 'f', singular: 'Kichererbse', plural: 'Kichererbsen', translation: 'Garbanzo', image: '', lesson: 7 },
    { genre: 'm', singular: 'Spargel', plural: 'Spargel', translation: 'Espárrago', image: '', lesson: 7 },
    { genre: 'f', singular: 'Nuss', plural: 'Nüsse', translation: 'Nuez', image: '', lesson: 7 },
    { genre: 'f', singular: 'Mandel', plural: 'Mandeln', translation: 'Almendra', image: '', lesson: 7 },
    { genre: 'f', singular: 'Haselnuss', plural: 'Haselnüsse', translation: 'Avellana', image: '', lesson: 7 },
    { genre: 'f', singular: 'Sahne', plural: '', translation: 'Nata', image: '', lesson: 7 },
    { genre: 'm', singular: 'Kuchen', plural: 'Kuchen', translation: 'Pastel', image: '', lesson: 7 },
    { genre: 'm', singular: 'Fisch', plural: 'Fische', translation: 'Pez / Pescado', image: '', lesson: 7 },
    { genre: 'f', singular: 'Lust', plural: '', translation: 'Ganas', image: '', lesson: 7 },
    { genre: 'm', singular: 'Senf', plural: 'Senfe', translation: 'Mostaza', image: '', lesson: 7 },
    { genre: 'n', singular: 'Öl', plural: 'Öle', translation: 'Aceite', image: '', lesson: 7 },
    { genre: 'n', singular: 'Hähnchen', plural: 'Hähnchen', translation: 'Pollo', image: '', lesson: 7 },
    { genre: 'm', singular: 'Hamburger', plural: 'Hamburger', translation: 'Hamburguesa', image: '', lesson: 7 },
    { genre: 'n', singular: 'Getränk', plural: 'Getränke', translation: 'Bebida', image: '', lesson: 7 },
    { genre: 'n', singular: 'Produkt', plural: 'Produkte', translation: 'Producto', image: '', lesson: 7 },
    { genre: 'f', singular: 'Traube', plural: 'Trauben', translation: 'Uva', image: '', lesson: 7 },
    { genre: 'm', singular: 'Knoblauch', plural: '', translation: 'Ajo', image: '', lesson: 7 },
    { genre: 'm', singular: 'Brokkoli', plural: '', translation: 'Brócoli', image: '', lesson: 7 }
];
