const verbs = [
    { value: 'hören', translation: 'oir', lesson: 1 },
    { value: 'l[e]sen', translation: 'leer', lesson: 1 },
    { value: 'spr[e]chen', translation: 'hablar', lesson: 1 },
    { value: 'kommen', translation: 'venir', lesson: 1 },
    { value: 'schreiben', translation: 'escribir', lesson: 1 },
    { value: 'heißen', translation: 'llamarse', lesson: 1 },
    { value: 'sein', translation: 'ser', lesson: 1 },
    { value: 'markieren', translation: 'marcar', lesson: 1 },
    { value: 'kennen', translation: 'conocer', lesson: 1 },
    { value: 'zeigen', translation: 'mostrar', lesson: 1 },
    { value: 'passen', translation: 'caber', lesson: 1 },
    { value: 'ergänzen', translation: 'completar', lesson: 1 },
    { value: 'antworten / beantworten', translation: 'contestar', lesson: 1 },
    { value: 'wohnen / leben', translation: 'vivir', lesson: 1 },
    { value: 'variieren', translation: 'variar', lesson: 1 },
    { value: 'gehen', translation: 'ir', lesson: 1 },
    { value: 'fragen', translation: 'preguntar', lesson: 1 },
    { value: 'mögen', translation: 'gustar', lesson: 1 },
    { value: 'kreuzen', translation: 'cruzar', lesson: 1 },
    { value: 'arbeiten', translation: 'trabajar', lesson: 1 },
    { value: 'notieren', translation: 'anotar', lesson: 1 },
    { value: 'stellen', translation: 'colocar', lesson: 1 },
    { value: 'hängen', translation: 'colgar', lesson: 1 },
    { value: 'singen', translation: 'cantar', lesson: 1 },
    { value: 'buchstabieren', translation: 'deletrear', lesson: 1 },
    { value: 'machen', translation: 'hacer', lesson: 2 },
    { value: 'ordnen', translation: 'ordenar', lesson: 2 },
    { value: 'tauschen', translation: 'cambiar', lesson: 2 },
    { value: 'ziehen', translation: 'tirar', lesson: 2 },
    { value: 'suchen', translation: 'buscar', lesson: 2 },
    { value: 'wählen', translation: 'elegir', lesson: 2 },
    { value: 'bleiben', translation: 'quedarse', lesson: 2 },
    { value: 'sagen', translation: 'decir', lesson: 2 },
    { value: 'kleben', translation: 'pegar', lesson: 3 },
    { value: 'setzen', translation: 'poner', lesson: 3 },
    { value: 'zählen', translation: 'contar', lesson: 3 },
    { value: 'erzählen', translation: 'narrar', lesson: 3 },
    { value: 's[e]hen', translation: 'ver', lesson: 3 },
    { value: 'fühlen', translation: 'sentir', lesson: 3 },
    { value: 'bringen', translation: 'traer', lesson: 3 },
    { value: 'berichten', translation: 'informar', lesson: 4 },
    { value: 'kaufen', translation: 'comprar', lesson: 4 },
    { value: 'brauchen', translation: 'necesitar', lesson: 4 },
    { value: 'unterstreichen', translation: 'subrayar', lesson: 4 },
    { value: 'denken', translation: 'pensar', lesson: 4 },
    { value: 'h[e]lfen', translation: 'ayudar', lesson: 4 },
    { value: 'glauben', translation: 'creer', lesson: 4 },
    { value: 'überprüfen', translation: 'revisar', lesson: 4 },
    { value: 'kosten', translation: 'costar', lesson: 4 },
    { value: 'haben', translation: 'tener', lesson: 4 },
    { value: 'r[a]ten', translation: 'recomendar', lesson: 4 },
    { value: 'spielen', translation: 'jugar', lesson: 4 },
    { value: 'finden', translation: 'encontrar', lesson: 4 },
    { value: 'besuchen', translation: 'visitar', lesson: 4 },
    { value: 'beschreiben', translation: 'describir', lesson: 4 },
    { value: 'bekommen', translation: 'recibir', lesson: 4 },
    { value: 'tanzen', translation: 'bailar', lesson: 5 },
    { value: 'wandern', translation: 'hacer senderismo', lesson: 5 },
    { value: 'fotografieren', translation: 'fotografiar', lesson: 5 },
    { value: 'f[a]hren', translation: 'ir (medio de transporte)', lesson: 5 },
    { value: 'kochen', translation: 'cocinar', lesson: 5 },
    { value: 'tr[e]ffen', translation: 'quedar con', lesson: 5 },
    { value: 'schwimmen', translation: 'nadar', lesson: 5 },
    { value: 'l[a]ufen', translation: 'correr', lesson: 5 },
    { value: 'treiben', translation: 'practicar (un deporte)', lesson: 5 },
    { value: 'aufstehen', translation: 'levantarse', separable: true, lesson: 5 },
    { value: 'g[e]ben', translation: 'dar', lesson: 5 },
    { value: 'schl[a]fen', translation: 'dormir', lesson: 5 },
    { value: 'w[a]schen', translation: 'lavar', lesson: 5 },
    { value: '[e]ssen', translation: 'comer', lesson: 5 },
    { value: 'malen', translation: 'pintar', lesson: 5 },
    { value: 'ferns[e]hen', translation: 'ver la televisión', separable: true, lesson: 5 },
    { value: 'schauen', translation: 'mirar', lesson: 5 },
    { value: 'feiern', translation: 'celebrar', lesson: 5 },
    { value: 'surfen', translation: 'surfear / navegar', lesson: 5 },
    { value: 'benutzen', translation: 'utilizar', lesson: 5 },
    { value: 'sammeln', translation: 'recoger / recaudar', lesson: 5 },
    { value: 'einl[a]den', translation: 'invitar', separable: true, lesson: 5 },
    { value: 'aufräumen', translation: 'ordenar', separable: true, lesson: 5 },
    { value: 'anrufen', translation: 'llamar por teléfono', separable: true, lesson: 5 },
    { value: 'losgehen', translation: 'irse', separable: true, lesson: 5 },
    { value: 'ausgehen', translation: 'salir', separable: true, lesson: 5 },
    { value: 'aufhören', translation: 'terminar', separable: true, lesson: 5 },
    { value: 'wegf[a]hren / abf[a]hren', translation: 'hacer una escapada', separable: true, lesson: 5 },
    { value: 'einkaufen', translation: 'hacer la compra', separable: true, lesson: 5 },
    { value: 'anziehen', translation: 'vestir', separable: true, lesson: 5 },
    { value: 'anf[a]ngen', translation: 'empezar', separable: true, lesson: 5 },
    { value: 'zurückkommen', translation: 'regresar de', separable: true, lesson: 5 },
    { value: 'spazieren', translation: 'pasear', lesson: 5 },
    { value: 'lernen', translation: 'aprender', lesson: 5 },
    { value: 'w[i]ssen', translation: 'saber', lesson: 5 },
    { value: 'f[a]ngen', translation: 'coger', lesson: 5 },
    { value: 'auss[e]hen', translation: 'parecer', separable: true, lesson: 6 },
    { value: 'verstehen', translation: 'entender', lesson: 6 },
    { value: 'stimmen', translation: 'ser correcto', lesson: 6 },
    { value: 'vorstellen', translation: 'presentar', separable: true, lesson: 6 },
    { value: 'w[o]llen', translation: 'querer', lesson: 6 },
    { value: 'posten', translation: 'postear', lesson: 6 },
    { value: 'hoffen', translation: 'esperar', lesson: 6 },
    { value: 'mitbringen', translation: 'traer / llevar', separable: true, lesson: 6 },
    { value: 'zusagen', translation: 'aceptar una invitación', separable: true, lesson: 6 },
    { value: 'absagen', translation: 'excusarse', separable: true, lesson: 6 },
    { value: 'anspr[e]chen', translation: 'dirigir la palabra a', separable: true, lesson: 6 },
    { value: 'ans[e]hen', translation: 'contemplar', separable: true, lesson: 6 },
    { value: 'vermissen', translation: 'echar de menos', lesson: 6 },
    { value: 'schenken', translation: 'regalar', lesson: 6 },
    { value: 'trinken', translation: 'beber', lesson: 7 },
    { value: 'm[ü]ssen', translation: 'tener que', lesson: 7 },
    { value: 'mitkommen', translation: 'venir(se) / acompañar', separable: true, lesson: 7 }
];